### ISSUE TITLE
What resources/references did you use?

### ISSUE THREAD

**Issue by RandoSY** [bsiever/microbit-pxt-blelog#4]
Hello!

To write this amazing code. I'm working with the Micro:bit v2, and am having trouble understanding what's what with the BLE support infrastructure, when you have to be paired, etc. Thought maybe I could talk to an expert.

Your C++ skills are black belt!

Thanks!!!

**Comment by bsiever** [comment]
Thanks for the compliment, but I'm definitely not a C++ expert.   There are several parts to the answer here:

1. I've done several BLE based projects and already knew _most_ of the concepts I was interested in using (independent of the micro:bit ecosystem). 
2. I had also worked the the Nordic BLE libraries outside of the micro:bit ecosystem.  So I knew some of the things I wanted to do and tricks to get it done.  The "BLE LOG" is two parts: the micro:bit end (this repo) and a corresponding Web Browser client:  https://github.com/bsiever/microbit-webblelog .    (My other bluetooth extension, BLE-HID, has to do several hacks to really work:  https://github.com/bsiever/microbit-pxt-blehid).  
3. Tangents you may be interested in too --- I had university students do a variety of related projects:
    * Web-based GUI to get and visualize the data: https://2024-ui-sp.github.io/Micro-bit-ble/ ([repo](https://github.com/2024-UI-SP/Micro-bit-ble))  
    * Flutter mobile app: https://github.com/masongaller/MicroSync
    * Another Flutter mobile app: https://github.com/a-jeck/microbit_app
4. I spent a lot of time looking at the source code to the micro:bit, both for the run-time (called CODAL) and for the MakeCode environment:
   * [codal-microbit-v2](https://github.com/lancaster-university/codal-microbit-v2/tree/master) --- Looks like you're already aware of that one.
   * [codal-microbit-v2's bluetooth](https://github.com/lancaster-university/codal-microbit-v2/tree/master/source/bluetooth)
   * [MakeCode Bluetooth API Source](https://github.com/microsoft/pxt-microbit/tree/master/libs/bluetooth)
5. And, of course, there was a fair amount of trial-and-error and debugging....

You may want to join the micro:bit developer Slack: https://github.com/microsoft/pxt-microbit/tree/master/libs/bluetooth (I also try to answer questions there if/when I can. It's pretty low traffic).  Sometimes the MakeCode forum is a good place for some MakeCode specific questions: https://forum.makecode.com/c/microbit

I hope that helps!
